<a href="https://colab.research.google.com/github/avisinghal6/GradCheck/blob/main/GradCheck.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
class ConvnetClassifier(torch.nn.Module):
    def __init__(self):
        super(ConvnetClassifier, self).__init__()
        self.linear1 = torch.nn.Linear(in_features = 2, out_features = 3,bias=False)
        self.linear2 = torch.nn.Linear(in_features = 3, out_features = 1,bias=False)

    def forward(self, x):
        # Pass through linear layers.
        x = self.linear1(x)
        print(x)
        x = torch.nn.functional.relu(x)
        print(x)
        x = self.linear2(x)
        print(x)
        x = torch.sigmoid(x)
        print(x)
        return x

# Test your model!
# Create dummy batch with 24 samples, where each is an image of size 3x48x48.
dummy_batch = torch.tensor([[1.0,-2.0],[5,-9.0],[-3,2]])
Y=torch.tensor([[0.1],[1],[0.8]])
my_model = ConvnetClassifier()
my_model.linear1.weight.data=torch.tensor([[1.0,-1.0],[0.0,0.0],[1.0,1.0]])
my_model.linear2.weight.data=torch.tensor([[1.0,0.0,-1.0]])

cost_function = torch.nn.MSELoss()
y=my_model(dummy_batch)
loss=cost_function(y,Y)
loss.backward()
for p in my_model.parameters():
  print(p.grad)
# predictions = my_model(dummy_batch)

# # Seems like working to me.
# print(dummy_batch.shape, predictions.shape)

tensor([[ 3.,  0., -1.],
        [14.,  0., -4.],
        [-5.,  0., -1.]], grad_fn=<MmBackward0>)
tensor([[ 3.,  0.,  0.],
        [14.,  0.,  0.],
        [ 0.,  0.,  0.]], grad_fn=<ReluBackward0>)
tensor([[ 3.],
        [14.],
        [ 0.]], grad_fn=<MmBackward0>)
tensor([[0.9526],
        [1.0000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
tensor([[ 0.0257, -0.0514],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000]])
tensor([[0.0770, 0.0000, 0.0000]])


In [ ]:
import numpy as np


In [ ]:
a=np.array([[3,14,0],[0,0,0],[0,0,0]]).T
d=np.array([[-0.85,0.01,0.3]])


In [ ]:
d

array([[-0.85,  0.01,  0.3 ]])

In [ ]:

e=np.array([[0.95,0.99,0.5]])
b=np.array([[0.05,0.01,0.5]])
f=d*e*b

In [ ]:
f

array([[-4.0375e-02,  9.9000e-05,  7.5000e-02]])

In [ ]:
ans=f@a

In [ ]:
ans*(-2.0/3.0)

array([[ 0.079826, -0.      , -0.      ]])

In [ ]:
ans*(-2.0/3.0)

array([[ 0.08075   ,  0.37683333, -0.        ]])

In [ ]:
x=np.array([[1,5,-3],[-2,-9,2]])
w2=np.array([[1,0,-1]])
a=np.array([[1.0,1.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.0]])
y=np.array([[-0.04,0.0,0.0075]])
ans=f.T@w2*a@x.T

In [ ]:
w2.shape

(1, 3)

In [ ]:
ans=ans*(-2.0/3.0)

In [ ]:
ans.T

array([[ 0.02691667, -0.        , -0.        ],
       [-0.05383333, -0.        , -0.        ]])